using Ext.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace OnlineHRS
{
    public partial class Default : System.Web.UI.Page
    {
        public static PersonnelInfo Personnel
        {
            get
            {
                //if(Session["UserInfo"] != null)
                //return Session["UserInfo"] as PersonnelInfo;
                return ApplicationSessionStateStore.GetItem<PersonnelInfo>("UserInfo");
            }
            set
            {
                //Session["UserInfo"] = value;
                ApplicationSessionStateStore.SetItem("UserInfo", value);
            }
        }

        public static string Decrypt(string encrypt)
        {
            return ApplicationSessionStateStore.EncryptMaping[encrypt];
           
        }
        //public static int CompanyID
        //{
        //    get
        //    {
        //        PersonnelInfo personnelInfo = Personnel;
        //        return personnelInfo.ParentID == null ? personnelInfo.ID : (int)personnelInfo.ParentID;
        //    }

        //}
        protected void Page_Load(object sender, EventArgs e)
        {
           
                

            string str = "";
            string DECT = Utility.Helper.Encrypt(str);
        }
        [DirectMethod(ShowMask = true, Msg = "...در حال بارگذاری سایت")]
        public void SiteLoader()
        {
            //RegisterModule("Modules/Company/CompanyManagement.ascx");
            //RegisterModule("Modules/Company/Registeration.ascx");

            RegisterModule("Modules/Company/CompanyRegisteration.ascx");
            RegisterModule("Modules/System/Login.ascx");
            //RegisterModule("Modules/System/LoginPersonnel.ascx");
            //RegisterModule("Modules/Company/CompanyManagement.ascx");

        }
        [DirectMethod()]
        public static string GetTokenID()
        {
            return HttpContext.Current.Session.SessionID;
        }
        public void RegisterModule(string path)
        {
            Control userControl;

            userControl = this.LoadControl(path);

            DesktopModuleProxy control = Ext.Net.Utilities.ControlUtils.FindControl<Ext.Net.DesktopModuleProxy>(userControl);
            //control.Module.Shortcut.SortIndex = 1;
            //List<Ext.Net.Observable> c1 = Ext.Net.Utilities.ControlUtils.FindControls<Ext.Net.Observable>(control.Module.Window[0], false);
            //Observable V = c1.Where(W => W.ID == "tabCompanyInfo").FirstOrDefault();
            //V.Enabled = false;
           control.RegisterModule();
            //Desktop1.Modules.Add(control.Module);

        }
        public void RemoveModule(params string[] moduleNames)
        {
            foreach (string moduleName in moduleNames)
                Desktop.GetInstance().RemoveModule(moduleName);
        }
        [DirectMethod()]
        public void SessionEnd()
        {
            Session.Abandon();
            HttpRequestManagement.AddRequest(HttpContext.Current.Request,"", "SessionEnd","");
            HttpRequestManagement.RemoveSession(Request);
            ApplicationSessionStateStore.RemoveAllItems();
        }

        private void Page_Error(object sender, EventArgs e)
        {
            // Get last error from the server
            Exception exc = Server.GetLastError();

            // Handle exceptions generated by Button 1
            if (exc is InvalidOperationException)
            {
                // Pass the error on to the Generic Error page
                Server.Transfer("GenericErrorPage.aspx", true);
            }

            // Handle exceptions generated by Button 2
            else if (exc is ArgumentOutOfRangeException)
            {
                // Give the user some information, but
                // stay on the default page
                Response.Write("<h2>Default Page Error</h2>\n");
                Response.Write("<p>Provide as much information here as is " + "appropriate to show to the client.</p>\n");
                Response.Write("Return to the <a href='Default.aspx'>" + "Default Page</a>\n");

                // Log the exception and notify system operators
                //ExceptionUtility.LogException(exc, "DefaultPage");
                //ExceptionUtility.NotifySystemOps(exc);

                // Clear the error from the server
                Server.ClearError();
            }
            else
            {
                // Pass the error on to the default global handler
            }
        }

    }


}

